name: Fetch upstream

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch from upstream
        run: |       
          git config --global user.name "github-actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # inspired by https://dev.to/ranewallin/how-to-keep-your-forked-repository-current-38mn
          
          # If you haven't already added an upstream source, set your upstream
          # to the fork's original source
          git remote add upstream "https://github.com/microsoft/fluentui-emoji"
          
          # Verify upstream is correct, you should see the URL for the upstream fetch and push 
          git remote -v
          
          # Get all recent branches and commits from the upstream
          git fetch upstream

          # Merge the branches and commits from the upstream
          git merge upstream/main --allow-unrelated-histories

          # helpful for debugging
          git show-ref

          git push
