name: Generate Twemoji

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-twemoji:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - run: |
          python converter/converter.py

      - name: Push updated emoji
        shell: pwsh
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config pull.rebase true

          git add export
          git commit -m "Generate twemoji"
          git pull
          git push

          exit 0

      - name: Keepalive Workflow
        if: always()
        uses: gautamkrishnar/keepalive-workflow@v2