# Run script to check asset data/metadata for consistency.

name: Generate Twemoji

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - run: |
          python converter/converter.py

      - name: Fetch from upstream
        env:
          GITHUB_TOKEN: ${{ github.token }}
          UPSTREAM: https://github.com/microsoft/fluentui-emoji
        run: |       
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          
          # inspired by https://dev.to/ranewallin/how-to-keep-your-forked-repository-current-38mn
          
          # If you haven't already added an upstream source, set your upstream
          # to the fork's original source
          git remote add upstream "${UPSTREAM}"
          
          # Verify upstream is correct, you should see the URL for the upstream fetch and push 
          git remote -v
          
          # Get all recent branches and commits from the upstream
          git fetch upstream
          
          # Merge the branches and commits from the upstream
          git merge upstream/main
                  
          # helpful for debugging
          git show-ref

          git push

      - name: Push updated manifest.txt
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config pull.rebase true

          git add export
          git commit -m "Generate twemoji"
          git pull
          git push

          exit 0

      - name: Keepalive Workflow
        if: always()
        uses: gautamkrishnar/keepalive-workflow@v2